[package]
name = "suwi-os"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = { version = "1.5.0", features = ["spin_no_std"]}
limine = "0.5.0"
spin = "0.10.0"
x86_64 = "0.15.4"

[profile.dev]
opt-level = 1
