[build]
target = "x86_64-unknown-none"
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-arg=-T/home/devnitrate/programming/suwi-os/linker.ld"
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]